apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-username: YWRtaW4=  # This is 'admin' base64 encoded
  mongodb-password: cGFzc3dvcmQ=  # This is 'password' base64 encoded
