apiVersion: v1
kind: Service
metadata:
  name: my-application-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30010
  selector:
    app: my-application
