# Default values for MongoDB.
replicaCount: 1
image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 27017
persistence:
  enabled: true
  storageClass: "manual"
  accessMode: ReadWriteOnce
  size: 10Gi
